<header>
  <div class="infobox">
    <div class="content">
      <h1><?= SITE_NAME ?></h1>
      <nav>
        <ul class="list-unstyled links">
          <li><a href="#">GitHub</a></li><!--
          --><li><a href="#">Stack Overflow</a></li><!--
          --><li><a href="#">LinkedIn</a></li><!--
          --><li><a href="#">Contact</a></li>
        </ul>
      </nav>
    </div>
  </div>
</header>
