<div class="container">
  <section class="row">
    <div class="col-md-3">
      <h2>About Me</h2>
    </div>

    <div class="col-md-9">
      <div class="about">
        <p>Lorem ipsum dolor sit amet, te sit unum convenire elaboraret, ei meis ullum inani qui. Atqui
          molestiae scripserit mei et. Ad vis scaevola ponderum temporibus, vidisse iracundia et pri, duo
          veniam appetere patrioque id. Eum ea vidisse admodum. Agam ponderum detraxit ex usu, ut malis timeam
          latine vel.</p>

        <p>Vix ei nihil discere, intellegat mediocritatem eum et, adhuc intellegam at vis. Sint vivendum
            deseruisse ex sed, mea viris splendide ne, no invidunt sapientem dissentias vim. Ad mei verterem
            torquatos vituperata. Sea enim maluisset reprehendunt id.</p>
        </div>
      </div>
  </section>
</div>
